name = "Amecs (Fabric)"
filename = "amecs-1.3.3+mc.20w45a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3177/357/amecs-1.3.3+mc.20w45a.jar"
hash-format = "murmur2"
hash = "3941008571"

[update]
[update.curseforge]
file-id = 3177357
project-id = 324564
release-channel = "beta"
