name = "AppleSkin"
filename = "appleskin-fabric-mc1.17-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/16/appleskin-fabric-mc1.17-2.0.0.jar"
hash-format = "murmur2"
hash = "1877344868"

[update]
[update.curseforge]
file-id = 3358016
project-id = 248787
release-channel = "beta"
