name = "Architectury API (Fabric)"
filename = "architectury-2.2.21-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3385/669/architectury-2.2.21-fabric.jar"
hash-format = "murmur2"
hash = "444399749"

[update]
[update.curseforge]
file-id = 3385669
project-id = 419697
release-channel = "beta"
