name = "Bits And Chisels"
filename = "bitsandchisels-2.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3336/685/bitsandchisels-2.5.0.jar"
hash-format = "murmur2"
hash = "86326765"

[update]
[update.curseforge]
file-id = 3336685
project-id = 420709
release-channel = "beta"
