name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.17-FABRIC-1.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3369/732/Croptopia-1.17-FABRIC-1.5.0.jar"
hash-format = "murmur2"
hash = "3346801440"

[update]
[update.curseforge]
file-id = 3369732
project-id = 415438
release-channel = "beta"
