name = "Dawn API"
filename = "dawn-2.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3403/253/dawn-2.0.4.jar"
hash-format = "murmur2"
hash = "877440239"

[update]
[update.curseforge]
file-id = 3403253
project-id = 399309
release-channel = "beta"
