name = "[Fabric] Expanded Storage"
filename = "expandedstorage-7.0.0-alpha.37+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3399/458/expandedstorage-7.0.0-alpha.37+1.17.1.jar"
hash-format = "murmur2"
hash = "2141837053"

[update]
[update.curseforge]
file-id = 3399458
project-id = 317856
release-channel = "beta"
