name = "Fabric Language Kotlin"
filename = "fabric-language-kotlin-1.6.2+kotlin.1.5.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3364/215/fabric-language-kotlin-1.6.2+kotlin.1.5.20.jar"
hash-format = "murmur2"
hash = "1941883754"

[update]
[update.curseforge]
file-id = 3364215
project-id = 308769
release-channel = "beta"
