name = "FerriteCore (Fabric)"
filename = "ferritecore-3.0.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3360/116/ferritecore-3.0.0-fabric.jar"
hash-format = "murmur2"
hash = "1456565004"

[update]
[update.curseforge]
file-id = 3360116
project-id = 459857
release-channel = "beta"
