name = "GeckoLib"
filename = "geckolib-fabric-1.17-3.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3364/165/geckolib-fabric-1.17-3.0.6.jar"
hash-format = "murmur2"
hash = "395976793"

[update]
[update.curseforge]
file-id = 3364165
project-id = 388172
release-channel = "beta"
