name = "Gotta Climb Fast!"
filename = "gottaclimbfast-1.17-3.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3351/588/gottaclimbfast-1.17-3.0-fabric.jar"
hash-format = "murmur2"
hash = "3125323045"

[update]
[update.curseforge]
file-id = 3351588
project-id = 392851
release-channel = "beta"
