name = "Happiness (is a) Warm Gun"
filename = "HWGMod-1.17-1.0.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3402/484/HWGMod-1.17-1.0.11.jar"
hash-format = "murmur2"
hash = "1171797152"

[update]
[update.curseforge]
file-id = 3402484
project-id = 448106
release-channel = "beta"
