name = "Industrial Revolution"
filename = "indrev-1.10.0-alpha.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3396/583/indrev-1.10.0-alpha.11.jar"
hash-format = "murmur2"
hash = "3192318308"

[update]
[update.curseforge]
file-id = 3396583
project-id = 391708
release-channel = "beta"
