name = "Industrial Revolution"
filename = "indrev-1.10.0-alpha.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3359/37/indrev-1.10.0-alpha.5.jar"
hash-format = "murmur2"
hash = "3523831360"

[update]
[update.curseforge]
file-id = 3359037
project-id = 391708
release-channel = "beta"
