name = "Mo' Structures (Fabric)"
filename = "mostructures-1.2.0-1.17-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3354/701/mostructures-1.2.0-1.17-fabric.jar"
hash-format = "murmur2"
hash = "2584247015"

[update]
[update.curseforge]
file-id = 3354701
project-id = 378266
release-channel = "beta"
