name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-3.4.0+1.17-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3399/382/notenoughcrashes-3.4.0+1.17-fabric.jar"
hash-format = "murmur2"
hash = "3220289667"

[update]
[update.curseforge]
file-id = 3399382
project-id = 353890
release-channel = "beta"
