name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-3.3.1+1.17-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3357/144/notenoughcrashes-3.3.1+1.17-fabric.jar"
hash-format = "murmur2"
hash = "4094157266"

[update]
[update.curseforge]
file-id = 3357144
project-id = 353890
release-channel = "beta"
