name = "Origins"
filename = "Origins-1.17-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3362/544/Origins-1.17-1.0.2.jar"
hash-format = "murmur2"
hash = "2222293756"

[update]
[update.curseforge]
file-id = 3362544
project-id = 391943
release-channel = "beta"
