name = "Rat's Mischief 🐀"
filename = "ratsmischief-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3360/105/ratsmischief-1.1.3.jar"
hash-format = "murmur2"
hash = "137643584"

[update]
[update.curseforge]
file-id = 3360105
project-id = 431787
release-channel = "beta"
