name = "Recipe Cache"
filename = "recipecache-0.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/298/recipecache-0.2.0.jar"
hash-format = "murmur2"
hash = "2896450921"

[update]
[update.curseforge]
file-id = 3348298
project-id = 473492
release-channel = "beta"
