name = "Tom's Simple Storage Mod (Fabric)"
filename = "tomsstorage-1.1.13-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3381/226/tomsstorage-1.1.13-1.17.1.jar"
hash-format = "murmur2"
hash = "2491100005"

[update]
[update.curseforge]
file-id = 3381226
project-id = 396826
release-channel = "beta"
