name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.12.2_Fabric_1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3365/444/Xaeros_Minimap_21.12.2_Fabric_1.17.jar"
hash-format = "murmur2"
hash = "1681147409"

[update]
[update.curseforge]
file-id = 3365444
project-id = 263420
release-channel = "beta"
